### ISSUE TITLE
Import Data?

### ISSUE THREAD

**Issue by faurkaurage** [high101bro/PoSh-EasyWin#11]
Hello Mr. Dan

I really enjoy your tool Posh EasyWin and have used it quite a bit to help analyze networks in the past. I recently downloaded the latest version and for the love of me can not find the 'import data' tab. I'm trying to import data from a new network I created from active directory but just can not find where to do that.  

Sorry for this dumb question, but can you point me in the right direction? You don't happen to have a Youtube channel where you showcase in video format how to use Posh do you?

Thanks again for all your hard work on this amazing tool

**Comment by high101bro** [comment]
It's simple, right-click on the computer tree-node section and select "Import Endpoint Data".
